# Generated by Django 3.0.3 on 2021-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210604_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(blank=None, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=10, null=True),
        ),
    ]
